name: Preview Deploy to GitHub Pages (Preview Branch)

on:
  push:
    branches:
      - 'testing-*'
      - 'preview/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 3. Build Astro site
      - name: Build Astro site
        run: npm run build

      # 4. Remove CNAME to avoid redirecting to custom domain
      - name: Remove CNAME for preview
        run: rm -f ./dist/CNAME || true

      # 5. Upload Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v1

      # 7. Show the preview URL
      - name: Show Preview URL
        run: |
            echo "Preview URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
